# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/libtins
pkgincludedir = $(includedir)/libtins
pkglibdir = $(libdir)/libtins
pkglibexecdir = $(libexecdir)/libtins
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
target_triplet = i686-pc-linux-gnu
subdir = .
DIST_COMMON = README $(am__configure_deps) $(libtins_HEADERS) \
	$(libtins_dot11_HEADERS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/libtins.pc.in \
	$(top_srcdir)/configure $(top_srcdir)/include/config.h.in \
	AUTHORS THANKS config.guess config.sub depcomp install-sh \
	ltmain.sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_cxx_compile_stdcxx_11.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/include/config.h
CONFIG_CLEAN_FILES = libtins.pc
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(pkgconfigdir)" \
	"$(DESTDIR)$(libtinsdir)" "$(DESTDIR)$(libtins_dot11dir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libtins_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libtins_la_OBJECTS = src/arp.lo src/bootp.lo \
	src/handshake_capturer.lo src/stp.lo src/pppoe.lo \
	src/crypto.lo src/dhcp.lo src/dhcpv6.lo src/dns.lo \
	src/dns_record.lo src/dot3.lo src/dot1q.lo src/eapol.lo \
	src/ethernetII.lo src/icmp.lo src/icmpv6.lo src/internals.lo \
	src/ip_reassembler.lo src/ip.lo src/ip_address.lo src/ipv6.lo \
	src/ipv6_address.lo src/ipsec.lo src/llc.lo src/loopback.lo \
	src/network_interface.lo src/packet_sender.lo \
	src/packet_writer.lo src/ppi.lo src/pdu.lo src/radiotap.lo \
	src/address_range.lo src/rawpdu.lo src/rsn_information.lo \
	src/sll.lo src/snap.lo src/sniffer.lo src/tcp.lo \
	src/tcp_stream.lo src/udp.lo src/utils.lo \
	src/dot11/dot11_base.lo src/dot11/dot11_data.lo \
	src/dot11/dot11_mgmt.lo src/dot11/dot11_beacon.lo \
	src/dot11/dot11_assoc.lo src/dot11/dot11_auth.lo \
	src/dot11/dot11_probe.lo src/dot11/dot11_control.lo
libtins_la_OBJECTS = $(am_libtins_la_OBJECTS)
libtins_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(libtins_la_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I. -I$(top_builddir)/include
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libtins_la_SOURCES)
DIST_SOURCES = $(libtins_la_SOURCES)
DATA = $(pkgconfig_DATA)
HEADERS = $(libtins_HEADERS) $(libtins_dot11_HEADERS)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/dev/git/libtins/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/dev/git/libtins/missing --run tar
AR = ar
AUTOCONF = ${SHELL} /home/dev/git/libtins/missing --run autoconf
AUTOHEADER = ${SHELL} /home/dev/git/libtins/missing --run autoheader
AUTOMAKE = ${SHELL} /home/dev/git/libtins/missing --run automake-1.11
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
HAVE_CXX11 = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = -lcrypto -lpcap 
LIBTINS_INCLUDE_DIR = include
LIBTINS_VERSION = 1:3:0
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAINT = 
MAKEINFO = ${SHELL} /home/dev/git/libtins/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = libtins
PACKAGE_BUGREPORT = matias.fontanini@gmail.com
PACKAGE_NAME = libtins
PACKAGE_STRING = libtins 1.3
PACKAGE_TARNAME = libtins
PACKAGE_VERSION = 1.3
PATH_SEPARATOR = :
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 1.3
abs_builddir = /home/dev/git/libtins
abs_srcdir = /home/dev/git/libtins
abs_top_builddir = /home/dev/git/libtins
abs_top_srcdir = /home/dev/git/libtins
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/dev/git/libtins/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = i686-pc-linux-gnu
target_alias = 
target_cpu = i686
target_os = linux-gnu
target_vendor = pc
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS} -I m4

# pkg-config stuff
pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = libtins.pc
lib_LTLIBRARIES = libtins.la
libtins_la_LDFLAGS = -version-info 1:3:0
AM_CXXFLAGS = -Wall -pedantic -Iinclude
libtins_la_SOURCES = src/arp.cpp \
                    src/bootp.cpp \
                    src/handshake_capturer.cpp \
                    src/stp.cpp \
                    src/pppoe.cpp \
                    src/crypto.cpp \
                    src/dhcp.cpp \
                    src/dhcpv6.cpp \
                    src/dns.cpp \
                    src/dns_record.cpp \
                    src/dot3.cpp \
                    src/dot1q.cpp \
                    src/eapol.cpp \
                    src/ethernetII.cpp \
                    src/icmp.cpp \
                    src/icmpv6.cpp \
                    src/internals.cpp \
                    src/ip_reassembler.cpp \
                    src/ip.cpp \
                    src/ip_address.cpp \
                    src/ipv6.cpp \
                    src/ipv6_address.cpp \
                    src/ipsec.cpp \
                    src/llc.cpp \
                    src/loopback.cpp \
                    src/network_interface.cpp \
                    src/packet_sender.cpp \
                    src/packet_writer.cpp \
                    src/ppi.cpp \
                    src/pdu.cpp \
                    src/radiotap.cpp \
                    src/address_range.cpp \
                    src/rawpdu.cpp \
                    src/rsn_information.cpp \
                    src/sll.cpp \
                    src/snap.cpp \
                    src/sniffer.cpp \
                    src/tcp.cpp \
                    src/tcp_stream.cpp \
                    src/udp.cpp \
                    src/utils.cpp \
                    src/dot11/dot11_base.cpp \
                    src/dot11/dot11_data.cpp \
                    src/dot11/dot11_mgmt.cpp \
                    src/dot11/dot11_beacon.cpp \
                    src/dot11/dot11_assoc.cpp \
                    src/dot11/dot11_auth.cpp \
                    src/dot11/dot11_probe.cpp \
                    src/dot11/dot11_control.cpp

libtinsdir = $(includedir)/tins
libtins_HEADERS = include/internals.h \
							include/dhcpv6.h \
							include/dot11.h \
							include/dot1q.h \
							include/dot3.h \
							include/small_uint.h \
							include/ip.h \
							include/ipsec.h \
							include/dns_record.h \
							include/eapol.h \
							include/tcp_stream.h \
							include/pppoe.h \
							include/handshake_capturer.h \
							include/ipv6.h \
							include/icmpv6.h \
							include/ieee802_3.h \
							include/endianness.h \
							include/rsn_information.h \
							include/loopback.h \
							include/ethernetII.h \
							include/crypto.h \
							include/packet.h \
							include/llc.h \
							include/ip_reassembler.h \
							include/icmp.h \
							include/hw_address.h \
							include/packet_writer.h \
							include/macros.h \
							include/arp.h \
							include/ip_address.h \
							include/pdu.h \
							include/packet_sender.h \
							include/bootp.h \
							include/network_interface.h \
							include/sll.h \
							include/ppi.h \
							include/radiotap.h \
							include/dns.h \
							include/rawpdu.h \
							include/sniffer.h \
							include/snap.h \
							include/pdu_cacher.h \
							include/dhcp.h \
							include/timestamp.h \
							include/tcp.h \
							include/pdu_option.h \
							include/tins.h \
							include/udp.h \
							include/ipv6_address.h  \
							include/constants.h \
							include/utils.h \
							include/cxxstd.h \
							include/stp.h \
							include/exceptions.h \
							include/config.h \
							include/address_range.h \
							include/pdu_allocator.h

libtins_dot11_HEADERS = include/dot11/dot11_base.h \
						include/dot11/dot11_beacon.h \
						include/dot11/dot11_data.h \
						include/dot11/dot11_mgmt.h \
						include/dot11/dot11_assoc.h \
						include/dot11/dot11_auth.h \
						include/dot11/dot11_probe.h \
						include/dot11/dot11_control.h

libtins_dot11dir = $(includedir)/tins/dot11/
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .lo .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

include/config.h: include/stamp-h1
	@if test ! -f $@; then \
	  rm -f include/stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) include/stamp-h1; \
	else :; fi

include/stamp-h1: $(top_srcdir)/include/config.h.in $(top_builddir)/config.status
	@rm -f include/stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status include/config.h
$(top_srcdir)/include/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f include/stamp-h1
	touch $@

distclean-hdr:
	-rm -f include/config.h include/stamp-h1
libtins.pc: $(top_builddir)/config.status $(srcdir)/libtins.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(libdir)" || $(MKDIR_P) "$(DESTDIR)$(libdir)"
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
src/$(am__dirstamp):
	@$(MKDIR_P) src
	@: > src/$(am__dirstamp)
src/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/$(DEPDIR)
	@: > src/$(DEPDIR)/$(am__dirstamp)
src/arp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/bootp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/handshake_capturer.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/stp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/pppoe.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/crypto.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dhcp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dhcpv6.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dns.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dns_record.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dot3.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dot1q.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/eapol.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ethernetII.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/icmp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/icmpv6.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/internals.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ip_reassembler.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/ip.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ip_address.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ipv6.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ipv6_address.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/ipsec.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/llc.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/loopback.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/network_interface.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/packet_sender.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/packet_writer.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/ppi.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/pdu.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/radiotap.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/address_range.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/rawpdu.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/rsn_information.lo: src/$(am__dirstamp) \
	src/$(DEPDIR)/$(am__dirstamp)
src/sll.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/snap.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/sniffer.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/tcp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/tcp_stream.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/udp.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/utils.lo: src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
src/dot11/$(am__dirstamp):
	@$(MKDIR_P) src/dot11
	@: > src/dot11/$(am__dirstamp)
src/dot11/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/dot11/$(DEPDIR)
	@: > src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_base.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_data.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_mgmt.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_beacon.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_assoc.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_auth.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_probe.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
src/dot11/dot11_control.lo: src/dot11/$(am__dirstamp) \
	src/dot11/$(DEPDIR)/$(am__dirstamp)
libtins.la: $(libtins_la_OBJECTS) $(libtins_la_DEPENDENCIES) 
	$(libtins_la_LINK) -rpath $(libdir) $(libtins_la_OBJECTS) $(libtins_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/address_range.$(OBJEXT)
	-rm -f src/address_range.lo
	-rm -f src/arp.$(OBJEXT)
	-rm -f src/arp.lo
	-rm -f src/bootp.$(OBJEXT)
	-rm -f src/bootp.lo
	-rm -f src/crypto.$(OBJEXT)
	-rm -f src/crypto.lo
	-rm -f src/dhcp.$(OBJEXT)
	-rm -f src/dhcp.lo
	-rm -f src/dhcpv6.$(OBJEXT)
	-rm -f src/dhcpv6.lo
	-rm -f src/dns.$(OBJEXT)
	-rm -f src/dns.lo
	-rm -f src/dns_record.$(OBJEXT)
	-rm -f src/dns_record.lo
	-rm -f src/dot11/dot11_assoc.$(OBJEXT)
	-rm -f src/dot11/dot11_assoc.lo
	-rm -f src/dot11/dot11_auth.$(OBJEXT)
	-rm -f src/dot11/dot11_auth.lo
	-rm -f src/dot11/dot11_base.$(OBJEXT)
	-rm -f src/dot11/dot11_base.lo
	-rm -f src/dot11/dot11_beacon.$(OBJEXT)
	-rm -f src/dot11/dot11_beacon.lo
	-rm -f src/dot11/dot11_control.$(OBJEXT)
	-rm -f src/dot11/dot11_control.lo
	-rm -f src/dot11/dot11_data.$(OBJEXT)
	-rm -f src/dot11/dot11_data.lo
	-rm -f src/dot11/dot11_mgmt.$(OBJEXT)
	-rm -f src/dot11/dot11_mgmt.lo
	-rm -f src/dot11/dot11_probe.$(OBJEXT)
	-rm -f src/dot11/dot11_probe.lo
	-rm -f src/dot1q.$(OBJEXT)
	-rm -f src/dot1q.lo
	-rm -f src/dot3.$(OBJEXT)
	-rm -f src/dot3.lo
	-rm -f src/eapol.$(OBJEXT)
	-rm -f src/eapol.lo
	-rm -f src/ethernetII.$(OBJEXT)
	-rm -f src/ethernetII.lo
	-rm -f src/handshake_capturer.$(OBJEXT)
	-rm -f src/handshake_capturer.lo
	-rm -f src/icmp.$(OBJEXT)
	-rm -f src/icmp.lo
	-rm -f src/icmpv6.$(OBJEXT)
	-rm -f src/icmpv6.lo
	-rm -f src/internals.$(OBJEXT)
	-rm -f src/internals.lo
	-rm -f src/ip.$(OBJEXT)
	-rm -f src/ip.lo
	-rm -f src/ip_address.$(OBJEXT)
	-rm -f src/ip_address.lo
	-rm -f src/ip_reassembler.$(OBJEXT)
	-rm -f src/ip_reassembler.lo
	-rm -f src/ipsec.$(OBJEXT)
	-rm -f src/ipsec.lo
	-rm -f src/ipv6.$(OBJEXT)
	-rm -f src/ipv6.lo
	-rm -f src/ipv6_address.$(OBJEXT)
	-rm -f src/ipv6_address.lo
	-rm -f src/llc.$(OBJEXT)
	-rm -f src/llc.lo
	-rm -f src/loopback.$(OBJEXT)
	-rm -f src/loopback.lo
	-rm -f src/network_interface.$(OBJEXT)
	-rm -f src/network_interface.lo
	-rm -f src/packet_sender.$(OBJEXT)
	-rm -f src/packet_sender.lo
	-rm -f src/packet_writer.$(OBJEXT)
	-rm -f src/packet_writer.lo
	-rm -f src/pdu.$(OBJEXT)
	-rm -f src/pdu.lo
	-rm -f src/ppi.$(OBJEXT)
	-rm -f src/ppi.lo
	-rm -f src/pppoe.$(OBJEXT)
	-rm -f src/pppoe.lo
	-rm -f src/radiotap.$(OBJEXT)
	-rm -f src/radiotap.lo
	-rm -f src/rawpdu.$(OBJEXT)
	-rm -f src/rawpdu.lo
	-rm -f src/rsn_information.$(OBJEXT)
	-rm -f src/rsn_information.lo
	-rm -f src/sll.$(OBJEXT)
	-rm -f src/sll.lo
	-rm -f src/snap.$(OBJEXT)
	-rm -f src/snap.lo
	-rm -f src/sniffer.$(OBJEXT)
	-rm -f src/sniffer.lo
	-rm -f src/stp.$(OBJEXT)
	-rm -f src/stp.lo
	-rm -f src/tcp.$(OBJEXT)
	-rm -f src/tcp.lo
	-rm -f src/tcp_stream.$(OBJEXT)
	-rm -f src/tcp_stream.lo
	-rm -f src/udp.$(OBJEXT)
	-rm -f src/udp.lo
	-rm -f src/utils.$(OBJEXT)
	-rm -f src/utils.lo

distclean-compile:
	-rm -f *.tab.c

include src/$(DEPDIR)/address_range.Plo
include src/$(DEPDIR)/arp.Plo
include src/$(DEPDIR)/bootp.Plo
include src/$(DEPDIR)/crypto.Plo
include src/$(DEPDIR)/dhcp.Plo
include src/$(DEPDIR)/dhcpv6.Plo
include src/$(DEPDIR)/dns.Plo
include src/$(DEPDIR)/dns_record.Plo
include src/$(DEPDIR)/dot1q.Plo
include src/$(DEPDIR)/dot3.Plo
include src/$(DEPDIR)/eapol.Plo
include src/$(DEPDIR)/ethernetII.Plo
include src/$(DEPDIR)/handshake_capturer.Plo
include src/$(DEPDIR)/icmp.Plo
include src/$(DEPDIR)/icmpv6.Plo
include src/$(DEPDIR)/internals.Plo
include src/$(DEPDIR)/ip.Plo
include src/$(DEPDIR)/ip_address.Plo
include src/$(DEPDIR)/ip_reassembler.Plo
include src/$(DEPDIR)/ipsec.Plo
include src/$(DEPDIR)/ipv6.Plo
include src/$(DEPDIR)/ipv6_address.Plo
include src/$(DEPDIR)/llc.Plo
include src/$(DEPDIR)/loopback.Plo
include src/$(DEPDIR)/network_interface.Plo
include src/$(DEPDIR)/packet_sender.Plo
include src/$(DEPDIR)/packet_writer.Plo
include src/$(DEPDIR)/pdu.Plo
include src/$(DEPDIR)/ppi.Plo
include src/$(DEPDIR)/pppoe.Plo
include src/$(DEPDIR)/radiotap.Plo
include src/$(DEPDIR)/rawpdu.Plo
include src/$(DEPDIR)/rsn_information.Plo
include src/$(DEPDIR)/sll.Plo
include src/$(DEPDIR)/snap.Plo
include src/$(DEPDIR)/sniffer.Plo
include src/$(DEPDIR)/stp.Plo
include src/$(DEPDIR)/tcp.Plo
include src/$(DEPDIR)/tcp_stream.Plo
include src/$(DEPDIR)/udp.Plo
include src/$(DEPDIR)/utils.Plo
include src/dot11/$(DEPDIR)/dot11_assoc.Plo
include src/dot11/$(DEPDIR)/dot11_auth.Plo
include src/dot11/$(DEPDIR)/dot11_base.Plo
include src/dot11/$(DEPDIR)/dot11_beacon.Plo
include src/dot11/$(DEPDIR)/dot11_control.Plo
include src/dot11/$(DEPDIR)/dot11_data.Plo
include src/dot11/$(DEPDIR)/dot11_mgmt.Plo
include src/dot11/$(DEPDIR)/dot11_probe.Plo

.cpp.o:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/.libs src/_libs
	-rm -rf src/dot11/.libs src/dot11/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pkgconfigdir)" || $(MKDIR_P) "$(DESTDIR)$(pkgconfigdir)"
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(pkgconfigdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(pkgconfigdir)" && rm -f $$files
install-libtinsHEADERS: $(libtins_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(libtinsdir)" || $(MKDIR_P) "$(DESTDIR)$(libtinsdir)"
	@list='$(libtins_HEADERS)'; test -n "$(libtinsdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(libtinsdir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(libtinsdir)" || exit $$?; \
	done

uninstall-libtinsHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(libtins_HEADERS)'; test -n "$(libtinsdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(libtinsdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(libtinsdir)" && rm -f $$files
install-libtins_dot11HEADERS: $(libtins_dot11_HEADERS)
	@$(NORMAL_INSTALL)
	test -z "$(libtins_dot11dir)" || $(MKDIR_P) "$(DESTDIR)$(libtins_dot11dir)"
	@list='$(libtins_dot11_HEADERS)'; test -n "$(libtins_dot11dir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(libtins_dot11dir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(libtins_dot11dir)" || exit $$?; \
	done

uninstall-libtins_dot11HEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(libtins_dot11_HEADERS)'; test -n "$(libtins_dot11dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(libtins_dot11dir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(libtins_dot11dir)" && rm -f $$files

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(DATA) $(HEADERS)
installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(libtinsdir)" "$(DESTDIR)$(libtins_dot11dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/$(am__dirstamp)
	-rm -f src/dot11/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/dot11/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libLTLIBRARIES clean-libtool \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf src/$(DEPDIR) src/dot11/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-libtinsHEADERS install-libtins_dot11HEADERS \
	install-pkgconfigDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf src/$(DEPDIR) src/dot11/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libLTLIBRARIES uninstall-libtinsHEADERS \
	uninstall-libtins_dot11HEADERS uninstall-pkgconfigDATA

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-libLTLIBRARIES clean-libtool ctags dist \
	dist-all dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-libLTLIBRARIES \
	install-libtinsHEADERS install-libtins_dot11HEADERS \
	install-man install-pdf install-pdf-am install-pkgconfigDATA \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-libLTLIBRARIES \
	uninstall-libtinsHEADERS uninstall-libtins_dot11HEADERS \
	uninstall-pkgconfigDATA


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
